spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybaitsplus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
#
#      elasticsearch:
#        rest:
#          uris: 192.168.10.149:9200
#          username: elastic
#          password: 5y8fzjhd78tqff37
#          geo:
#            distance: 50000



logging:
  level:
    com:
      example:
        mapper : debug
