spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybaitsplus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200



logging:
  level:
    com:
      example:
        mapper : debug
